# ==================
# 로컬 개발용
# ==================
spring:
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: my-super-long-secret-key-that-is-over-32-bytes
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000